# -*- coding: utf-8 -*-
"""week16

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a_yO5vSrbU3glBI65EVCjq2kqQnsigLN

# **MEDICAL INSURANCE COST ANALYSIS & PREDICTION SYSTEM**

### **INSTALL REQUIRED LIBRARIES**
"""

!pip install plotly -q

"""### **IMPORT LIBRARIES**"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    r2_score,
    mean_absolute_error,
    mean_squared_error,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

import plotly.express as px

"""### **CONNECT GOOGLE DRIVE**"""

drive.mount('/content/drive')

"""### **LOAD DATASET**"""

file_path = "/content/drive/MyDrive/Colab Notebooks/insurance.csv"
df = pd.read_csv(file_path)
print("Dataset Loaded Successfully")
print("Dataset Shape :", df.shape)
display(df.head())

"""### **DATASET INFORMATION**"""

print("\nDataset Information")
print(df.info())

print("\nMissing Values")
print(df.isnull().sum())

print("\nDuplicate Rows")
print(df.duplicated().sum())

df = df.drop_duplicates()

"""### **DESCRIPTIVE STATISTICS**"""

print("\nSummary Statistics")
display(df.describe())
print("\nAverage Age :", df["age"].mean())
print("Average BMI :", df["bmi"].mean())
print("Average Children :", df["children"].mean())
print("Average Charges :", df["charges"].mean())

"""### **EXPLORATORY DATA ANALYSIS**"""

plt.figure(figsize=(8,5))
sns.histplot(df["age"], kde=True)
plt.title("Age Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["bmi"], kde=True)
plt.title("BMI Distribution")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df["charges"], kde=True)
plt.title("Insurance Charges Distribution")
plt.show()

"""### **INSURANCE COST ANALYSIS**"""

print("\nAverage Charges by Gender")
print(df.groupby("sex")["charges"].mean())

print("\nAverage Charges by Smoker")
print(df.groupby("smoker")["charges"].mean())

print("\nAverage Charges by Region")
print(df.groupby("region")["charges"].mean())

print("\nAverage Charges by Children")
print(df.groupby("children")["charges"].mean())

"""### **AGE GROUP ANALYSIS**"""

df["Age_Group"] = pd.cut(
    df["age"],
    bins=[0,20,40,60,100],
    labels=["Teen","Adult","Middle Age","Senior"]
)

print("\nAge Group Charges")
print(df.groupby("Age_Group")["charges"].mean())

"""### **BMI CATEGORY ANALYSIS**"""

df["BMI_Category"] = pd.cut(
    df["bmi"],
    bins=[0,18.5,25,30,100],
    labels=[
        "Underweight",
        "Normal",
        "Overweight",
        "Obese"
    ]
)

print("\nBMI Category Charges")
print(df.groupby("BMI_Category")["charges"].mean())

"""### **VISUALIZATION**"""

plt.figure(figsize=(8,5))
sns.scatterplot(data=df,x="age",y="charges")
plt.title("Age vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.scatterplot(data=df,x="bmi",y="charges")
plt.title("BMI vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df,x="smoker",y="charges")
plt.title("Smoker vs Charges")
plt.show()

plt.figure(figsize=(8,5))
sns.boxplot(data=df,x="sex",y="charges")
plt.title("Gender vs Charges")
plt.show()

"""### **PIE CHARTS**"""

df["sex"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)
plt.title("Gender Distribution")
plt.ylabel("")
plt.show()

df["smoker"].value_counts().plot(
    kind="pie",
    autopct="%1.1f%%"
)
plt.title("Smoker Distribution")
plt.ylabel("")
plt.show()

"""### **ENCODING**"""

data = df.copy()

le = LabelEncoder()

data["sex"] = le.fit_transform(data["sex"])
data["smoker"] = le.fit_transform(data["smoker"])
data["region"] = le.fit_transform(data["region"])

"""### **CORRELATION HEATMAP**"""

plt.figure(figsize=(10,6))

sns.heatmap(
    data.corr(numeric_only=True),
    annot=True,
    cmap="coolwarm"
)

plt.title("Correlation Heatmap")
plt.show()

"""### **RISK ANALYSIS**"""

low = data["charges"].quantile(0.33)
high = data["charges"].quantile(0.66)

def risk_category(x):

    if x <= low:
        return "Low Risk"

    elif x <= high:
        return "Medium Risk"

    else:
        return "High Risk"

data["Risk_Category"] = data["charges"].apply(risk_category)

print("\nRisk Category Count")
print(data["Risk_Category"].value_counts())

"""### **SIMPLE LINEAR REGRESSION**"""

print("\n==============================")
print("SIMPLE LINEAR REGRESSION")
print("==============================")

X = data[["age"]]
y = data["charges"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

model = LinearRegression()

model.fit(X_train,y_train)

pred = model.predict(X_test)

print("R2 Score :", r2_score(y_test,pred))
print("MAE :", mean_absolute_error(y_test,pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test,pred)))

"""### **MULTIPLE LINEAR REGRESSION**"""

print("\n==============================")
print("MULTIPLE LINEAR REGRESSION")
print("==============================")

X = data[["age","bmi","children","smoker"]]
y = data["charges"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

mlr = LinearRegression()

mlr.fit(X_train,y_train)

pred = mlr.predict(X_test)

print("R2 Score :", r2_score(y_test,pred))
print("MAE :", mean_absolute_error(y_test,pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test,pred)))

"""### **LOGISTIC REGRESSION**"""

print("\n==============================")
print("LOGISTIC REGRESSION")
print("==============================")

median_charge = data["charges"].median()

data["Insurance_Class"] = np.where(
    data["charges"] > median_charge,
    1,
    0
)

X = data[["age","bmi","children","smoker"]]
y = data["Insurance_Class"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

log_model = LogisticRegression()

log_model.fit(X_train,y_train)

pred = log_model.predict(X_test)

print("Accuracy :", accuracy_score(y_test,pred))
print("Precision :", precision_score(y_test,pred))
print("Recall :", recall_score(y_test,pred))
print("F1 Score :", f1_score(y_test,pred))

print("\nClassification Report")
print(classification_report(y_test,pred))

cm = confusion_matrix(y_test,pred)

plt.figure(figsize=(6,4))
sns.heatmap(cm,annot=True,fmt="d")
plt.title("Confusion Matrix")
plt.show()

"""### **RANDOM FOREST REGRESSOR**"""

print("\n==============================")
print("RANDOM FOREST REGRESSOR")
print("==============================")

X = data[["age","bmi","children","smoker"]]
y = data["charges"]

X_train,X_test,y_train,y_test = train_test_split(
    X,y,test_size=0.2,random_state=42
)

rf = RandomForestRegressor(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train,y_train)

rf_pred = rf.predict(X_test)

print("R2 Score :", r2_score(y_test,rf_pred))
print("MAE :", mean_absolute_error(y_test,rf_pred))
print("RMSE :", np.sqrt(mean_squared_error(y_test,rf_pred)))

"""### **FEATURE IMPORTANCE**"""

importance = pd.DataFrame({
    "Feature": X.columns,
    "Importance": rf.feature_importances_
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print("\nFeature Importance")
display(importance)

"""### **PLOTLY DASHBOARD**"""

fig = px.histogram(
    df,
    x="charges",
    title="Insurance Charges Distribution"
)
fig.show()

fig = px.scatter(
    df,
    x="age",
    y="charges",
    color="smoker",
    title="Age vs Charges"
)
fig.show()

fig = px.scatter(
    df,
    x="bmi",
    y="charges",
    color="smoker",
    title="BMI vs Charges"
)
fig.show()

"""### **USER PREDICTION**"""

print("\n==============================")
print("INSURANCE COST PREDICTION")
print("==============================")

age = float(input("Enter Age : "))
bmi = float(input("Enter BMI : "))
children = int(input("Enter Number of Children : "))
smoker = int(input("Smoker (1=Yes,0=No) : "))

sample = pd.DataFrame({
    "age":[age],
    "bmi":[bmi],
    "children":[children],
    "smoker":[smoker]
})

prediction = rf.predict(sample)

print("\nPredicted Insurance Charge = ₹",
      round(prediction[0],2))

"""### **END**"""

print("\nPROJECT COMPLETED SUCCESSFULLY")